### ISSUE TITLE
关于参数化实现疑问

### ISSUE THREAD

**Issue by uclive1525** [liuyunlong1229/swagger2jmx-plugin#1]
swagger接口文档对于每一个参数有一个数据类型，如何根据数据类型生成随机参数。
比如说int或者String生成一些随机测试参数。

运行时有抛错：
生成openApinull
java.lang.NullPointerException
	at com.lyl.plugin.generate.MyDefaultGenerator.prepareTemplateData(MyDefaultGenerator.java:101)
	at com.lyl.plugin.generate.MyDefaultGenerator.generate(MyDefaultGenerator.java:60)
	at com.lyl.plugin.JmxGenerator.main(JmxGenerator.java:54)

**Comment by liuyunlong1229** [comment]
现在应该不支持，你的这个错误是怎么报出来的，能否描述下

**Comment by liuyunlong1229** [comment]
> swagger接口文档对于每一个参数有一个数据类型，如何根据数据类型生成随机参数。
> 比如说int或者String生成一些随机测试参数。
> 
> 运行时有抛错：
> 生成openApinull
> java.lang.NullPointerException
> at com.lyl.plugin.generate.MyDefaultGenerator.prepareTemplateData(MyDefaultGenerator.java:101)
> at com.lyl.plugin.generate.MyDefaultGenerator.generate(MyDefaultGenerator.java:60)
> at com.lyl.plugin.JmxGenerator.main(JmxGenerator.java:54)

能否描述在这个错误的测试场景

**Comment by uclive1525** [comment]
就通过SWAGGER_LOCATION配置swagger接口地址，然后三个项目，只有一个正常生成jmx文件。其它两个都抛错

**Comment by uclive1525** [comment]
swagger接口返回的json的paths/接口url/get/parameters/type来做参数化判断依据。
想通过你这个思想改造成直接通过http request去访问所有接口，通过code=200来做一次断言，进行接口的初测。

**Comment by liuyunlong1229** [comment]
> 就通过SWAGGER_LOCATION配置swagger接口地址，然后三个项目，只有一个正常生成jmx文件。其它两个都抛错

最好能提供离线版swagger的json串。

**Comment by uclive1525** [comment]
找到原因了，应该是根据swagger接口地址解析成json时抛的异常。
我若把swagger接口地址请求后把数据成为json，就可以正常生成jmx文件。
可能是数据超长造成，wagger接口地址接口较少的就可直接根据url生成jmx文件

**Comment by uclive1525** [comment]
由于PUT请求导致，已解决，MyDefaultGenerator.java
if (operation.getRequestBody() != null) {
            RequestBody requestBody = path.getPost().getRequestBody();
            requestBody = ModelUtils.getReferencedRequestBody(this.openAPI, requestBody);
            Map<String, Schema> schemas = ModelUtils.getSchemas(this.openAPI);
修改为：
        if (operation.getRequestBody() != null) {
            RequestBody requestBody = operation.getRequestBody();
            requestBody = ModelUtils.getReferencedRequestBody(this.openAPI, requestBody);
            Map<String, Schema> schemas = ModelUtils.getSchemas(this.openAPI);
